language: python
python:
  - "3.8"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: 
  - python -m unittest
  - coverage run tests
after_success:
  - coveralls